name: Laravel CI

on:
  pull_request:
    branches: ["main", "develop"]

jobs:
  laravel-tests:
    name: Run Tests & Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Sesuaikan dengan versi PHP server Anda

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Check Code Styling (Pint)
        run: ./vendor/bin/pint --test

      # Tambahkan step Larastan di sini
      - name: Run Static Analysis (Larastan)
        run: ./vendor/bin/phpstan analyse --error-format=github

      - name: Run Tests (Pest/PHPUnit)
        run: php artisan test
